DROP DATABASE IF EXISTS `user_db`;
CREATE DATABASE `user_db`;
USE `user_db`;

CREATE TABLE `users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL
);